#这些配置会被保留，如果和下面的重复则会被覆盖
spring:
  profiles:
    active: dev

  datasource:
    master:
      url: jdbc:mysql://192.168.0.4/mytest?serverTimezone=Hongkong
      username: root
      password: root
      initialSize: 5
      maxActive: 6
      filters: stat,wall
    slave:
      url: jdbc:mysql://192.168.0.5/mytest?serverTimezone=Hongkong
      username: root
      password: root
      initialSize: 5
      maxActive: 6
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.my.model
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
---
#当环境为dev时采用该配置
spring:
  profiles: dev
server:
  port: 8080

msg: i am dev
---
#当环境为prod时采用该配置
spring:
  profiles: prod
server:
  port: 8082
#自定义
msg: i am prod