#这些配置会被保留，如果和下面的重复则会被覆盖
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost/mytest?serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml

---
#当环境为dev时采用该配置
spring:
  profiles: dev
server:
  port: 8080
msg: i am dev
---
#当环境为prod时采用该配置
spring:
  profiles: prod
server:
  port: 8082
#自定义
msg: i am prod