
spring:
  datasource:
    url: jdbc:mysql://localhost/mytest?serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80

mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml